# Generated by Django 5.1.3 on 2025-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='qollanma',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Fayl'),
        ),
    ]
